### ISSUE TITLE
Maybe impl `std::fmt::Display`

### ISSUE THREAD

**Issue by mvertescher** [Eonm/nl80211#2]
It's a little strange that types in this repo implement a custom printing trait `PrettyFormat`. The [`Display` trait](https://doc.rust-lang.org/std/fmt/trait.Display.html) is typically used in this situation. 

Perhaps we can migrate `PrettyFormat` impls to `std::fmt::Display`. This would ease usage, for example:

```rust
// This
println!("{}", interface);

// Instead of below
// println!("{}\n", interface.pretty_format());
```

**Comment by Eonm** [comment]
Sorry for the late reply.

You're right, it would be more idiomatic Rust.

I implemented `fmt::Display` for all structs which implemented .pretty_print() 9d233df
